#!/bin/sh

mv /etc/banner /etc/banner_tmp

# add Omega ascii art
OMEGA="
      ttttt w     w i 
        t    w   w  i
	t    w w w  i
	t     w w   i
        t      w    i
" 

echo "$OMEGA" > /etc/banner

# add Omega firmware version
version=$(uci get onion.@onion[0].version)
build=$(uci get onion.@onion[0].build)
echo " -----------------------------------------------------" >> /etc/banner
echo "   twin-ware: $version b$build" >> /etc/banner
echo " -----------------------------------------------------" >> /etc/banner

# old code to preserve bottom of old banner
#sed -e 9,14d -e 1,5d /etc/banner_tmp | cat >> /etc/banner

rm /etc/banner_tmp

